{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-env" .Release.Name) .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret }}
  {{ $k }}: {{ $v | toString | quote }}
  {{- end }}
{{- end }}
